version: '3.3'

services:
  rabbit1:
    build: .
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - postgres
    labels:
      NAME: "rabbitmq1"
  postgres:
      image: mdillon/postgis:9.6-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: changeme
        PGDATA: /data/postgres
      ports:
        - "5433:5432"    
      networks:
        - postgres
      restart: unless-stopped
networks:
  postgres:
    driver: bridge